### ISSUE TITLE
Nullpointer by SummeWarenWert

### ISSUE THREAD

**Issue by wolfgangmessner** [wolfgangmessner/Reko30#3]
-> Akt bearbeiten (Rechnung 81609345)
-> Belas auswählen und Cmd Beleg stornieren
  -> Begründung auswählen, Fehler bei Ok

java.lang.NullPointerException
	at at.hafina.zentrale.rechnungDATA.Rechnung.getSummeWarenWert(Rechnung.java:865)
	at at.hafina.reko.rekoPROC.RekoService$17.select(RekoService.java:496)

**Comment by wolfgangmessner** [comment]
-> Akt bearbeiten (Rechnung 81543120)
-> Belas auswählen und Cmd Beleg stornieren
  -> Begründung auswählen, Fehler bei Ok
